"use client";
import Link from "next/link";
import Nav from "@/components/Nav";
export default function SupportPage() {
return <main className="legalRoot"><div className="legalShell"><Nav/>
<header className="legalHero"><p className="legalEyebrow">HPS · SUPPORT</p><h1>Support</h1><p>Help with the HPS website, Research Agent, browser extension, Microsoft Word add-in, signing and verification.</p><div className="legalMeta"><span>Human Provenance Standard</span><span>Technical & product support</span></div></header>
<article className="legalContent">
<section><h2>Contact</h2><div className="supportCards"><div className="supportCard"><h3>General support</h3><p>Product, technical and account assistance.</p><div className="supportCode">support@humanprovenancestandard.org</div></div><div className="supportCard"><h3>Privacy</h3><p>Privacy and data-protection requests.</p><div className="supportCode">privacy@humanprovenancestandard.org</div></div></div><p>When reporting a technical issue, include what you were trying to do, the page or integration involved, the error message, browser or Word environment and a screenshot where appropriate. Never send passwords or private signing keys.</p></section>
<section><h2>Browser extension</h2><p>The extension lets you deliberately save the current page as a research source, record AI assistance, record human review, create checkpoints, export the trail and send it into the HPS Research Agent.</p><p>For development installation: open <strong>chrome://extensions</strong>, enable Developer mode, choose <strong>Load unpacked</strong>, and select the folder that directly contains <strong>manifest.json</strong>.</p><p>A public Chrome Web Store flow may be offered after store approval.</p></section>
<section><h2>Microsoft Word add-in</h2><p>The HPS Word add-in supports explicit document or selection audits, document hashing, citation checks, AI-assistance disclosure and transfer into the HPS Research Agent. Development versions may require sideloading the Word manifest. A public Microsoft Marketplace flow may be offered after approval.</p></section>
<section><h2>Research Agent</h2><p>The Research Agent can capture sources, verify DOI metadata, link claims to evidence, record AI assistance, surface integrity warnings, record human review, create checkpoints and export a provenance trail. Parts of the current prototype may be stored locally in the browser, so clearing browser storage can remove local session data.</p><div className="legalLinks"><Link className="legalButton primary" href="/research-agent">Open Research Agent</Link></div></section>
<section><h2>Signing and keys</h2><p>Creator signing keys may be encrypted locally with a passphrase. Keep both the private key and passphrase secure.</p><div className="legalCallout"><strong>HPS support will never ask you to send your private signing key or password.</strong></div></section>
<section><h2>Verification</h2><p>If a record does not verify, check that you are using the exact file or data originally registered, that the record has not been revoked or superseded and that the relevant public key or institutional record is available.</p><div className="legalLinks"><Link className="legalButton" href="/verify">Open verification</Link><Link className="legalButton" href="/records">View registry</Link></div></section>
<section><h2>Privacy requests</h2><p>For privacy questions or data requests, contact privacy@humanprovenancestandard.org and review the HPS Privacy Policy.</p><div className="legalLinks"><Link className="legalButton primary" href="/privacy">Privacy Policy</Link><Link className="legalButton" href="/terms">Terms</Link></div></section>
</article></div>
<style jsx global>{`
.legalRoot{min-height:100vh;background:#0c0d0f;color:#f1eee7}.legalShell{max-width:1080px;margin:0 auto;padding:58px 24px 90px}.legalHero{max-width:850px;padding:52px 0 34px;border-bottom:1px solid #282a2f}.legalEyebrow{color:#c69a5b;font-size:11px;font-weight:800;letter-spacing:.17em;text-transform:uppercase;margin-bottom:16px}.legalHero h1{font-size:clamp(42px,6vw,70px);line-height:1;letter-spacing:-.045em;margin:0 0 20px}.legalHero p,.legalContent p,.legalContent li{color:#9fa2a7;line-height:1.7}.legalMeta{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.legalMeta span{border:1px solid #33363b;background:#141619;border-radius:999px;color:#92959a;font-size:11px;padding:7px 10px}.legalContent{max-width:820px;margin:34px auto 0}.legalContent section{padding:0 0 28px;margin-bottom:28px;border-bottom:1px solid #24262b}.legalContent h2{font-size:25px;margin:0 0 13px}.legalContent h3{font-size:17px;margin:20px 0 9px}.legalCallout{border:1px solid #35383e;background:#111315;border-radius:14px;padding:17px 18px;margin:18px 0}.legalLinks{display:flex;gap:9px;flex-wrap:wrap;margin-top:32px}.legalButton{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 15px;border-radius:10px;border:1px solid #373a40;background:#17191c;color:#eeeae2;text-decoration:none;font-size:12px;font-weight:750}.legalButton.primary{background:#ede7dc;color:#111315;border-color:#ede7dc}.supportCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.supportCard{border:1px solid #2d3035;background:#101214;border-radius:14px;padding:18px}.supportCode{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#cab28e;background:#0a0c0e;border:1px solid #282b30;border-radius:9px;padding:10px;overflow-wrap:anywhere}
`}</style>
</main>;
}