"use client";
import { use,useEffect,useState } from "react";
import Nav from "@/components/Nav";
import { createIssuerKey,getIssuerPublicKey,signIssuerClaim } from "@/lib/hps/issuer-keyvault";
async function hashFile(file:File){const d=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
export default function Page({params}:{params:Promise<{id:string}>}){
  const {id}=use(params); const [org,setOrg]=useState<any>(null),[role,setRole]=useState(""),[pk,setPk]=useState<string|null>(null),[keyId,setKeyId]=useState(""),[pass,setPass]=useState(""),[title,setTitle]=useState(""),[documentType,setDocumentType]=useState("official_letter"),[subjectName,setSubjectName]=useState(""),[fileName,setFileName]=useState(""),[assetHash,setAssetHash]=useState(""),[msg,setMsg]=useState("");
  const [dups,setDups]=useState<any[]>([]),[relatedRecordId,setRelatedRecordId]=useState(""),[relationshipType,setRelationshipType]=useState("");
  const [eType,setEType]=useState("registration_certificate"),[regNo,setRegNo]=useState(""),[eNote,setENote]=useState(""),[eFile,setEFile]=useState<File|null>(null),[evidence,setEvidence]=useState<any[]>([]),[eMsg,setEMsg]=useState("");
  async function loadEvidence(){const r=await fetch(`/api/organizations/${id}/verification-evidence`,{cache:"no-store"});if(r.ok){const d=await r.json();setEvidence(d.evidence||[])}}
  useEffect(()=>{(async()=>{const r=await fetch("/api/organizations");const d=await r.json();const row=(d.organizations||[]).find((x:any)=>x.hps_organizations?.id===id);setOrg(row?.hps_organizations);setRole(row?.role||"");const localPk=getIssuerPublicKey(id);setPk(localPk);if(localPk){const kr=await fetch(`/api/organizations/${id}/keys`);if(kr.ok){const kd=await kr.json();const match=(kd.keys||[]).find((k:any)=>k.public_key===localPk);if(match)setKeyId(match.id)}}await loadEvidence()})();},[id]);
  async function makeKey(){if(pass.length<10)return setMsg("Use an issuer-key passphrase of at least 10 characters.");const publicKey=await createIssuerKey(id,pass);setPk(publicKey);const r=await fetch(`/api/organizations/${id}/keys`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicKey,label:"Primary issuer key"})});const d=await r.json();if(r.ok){setKeyId(d.key.id);setMsg("Issuer key registered.")}else setMsg(d.error||"Unable to register issuer key.")}
  async function chooseFile(f?:File){if(!f)return;setFileName(f.name);const h=await hashFile(f);setAssetHash(h);setDups([]);setRelationshipType("");const r=await fetch(`/api/organizations/${id}/asset-check?hash=${h}`);if(r.ok){const d=await r.json();if((d.sameOrganization||[]).length)setMsg("This exact asset is already registered by this institution. Use versioning instead.");else if((d.otherOrganizations||[]).length){setDups(d.otherOrganizations);setRelatedRecordId(d.otherOrganizations[0].id);setMsg("This exact asset is already registered by another institution. Declare the relationship below.");}else setMsg("No existing institutional claim found for this exact asset.")}}
  async function uploadEvidence(){if(!eFile)return setEMsg("Choose an evidence file.");const f=new FormData();f.set("file",eFile);f.set("evidenceType",eType);f.set("registrationNumber",regNo);f.set("note",eNote);const r=await fetch(`/api/organizations/${id}/verification-evidence`,{method:"POST",body:f});const d=await r.json();if(!r.ok)return setEMsg(d.error||"Unable to upload evidence.");setEMsg("Verification evidence uploaded privately.");setEFile(null);await loadEvidence()}
  async function issue(){if(!org||!pk||!keyId)return setMsg("Register an issuer key first.");if(dups.length&&(!relatedRecordId||!relationshipType))return setMsg("Declare the relationship to the existing HPS record.");const claim={organizationId:id,organizationName:org.name,documentType,title,subjectName:subjectName||undefined,fileName:fileName||undefined,assetHash,issuerPublicKey:pk,issuerKeyId:keyId,parentRecordId:null,issuedAt:new Date().toISOString()};try{const s=await signIssuerClaim(id,claim,pass);const body:any={institutionalClaim:claim,institutionSignature:s.signature};if(dups.length)body.assetRelationship={relatedRecordId,relationshipType};const r=await fetch(`/api/organizations/${id}/issue`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMsg(r.ok?`Issued ${d.id}`:d.error||"Unable to issue record.")}catch(e:any){setMsg(e.message)}}
  if(!org)return <main className="pageShell"><Nav/><div className="loading">Loading institution…</div></main>;
  return <main className="pageShell"><Nav/><header className="pageHead shell"><p className="eyebrow">HPS INSTITUTIONAL ISSUER</p><h1>{org.name}</h1><p>Verification: <strong>{org.verification_status}</strong> · Your role: <strong>{role}</strong></p></header><section className="panel"><div className="formGrid">
    <div className="sectionLabel">00 · Institution verification evidence</div>
    <div className="field"><label>Evidence type</label><select value={eType} onChange={e=>setEType(e.target.value)}><option value="registration_certificate">Registration certificate</option><option value="government_registry">Government/regulator registry</option><option value="authorization_letter">Authorization letter</option><option value="operating_licence">Operating licence</option><option value="other">Other</option></select></div>
    <div className="field"><label>Registration/licence number</label><input value={regNo} onChange={e=>setRegNo(e.target.value)}/></div>
    <div className="field"><label>Evidence file (private)</label><input type="file" accept=".pdf,image/jpeg,image/png,image/webp" onChange={e=>setEFile(e.target.files?.[0]||null)}/></div>
    <div className="field"><label>Note</label><input value={eNote} onChange={e=>setENote(e.target.value)}/></div>
    <div className="field full"><button className="button secondary" onClick={uploadEvidence} disabled={!eFile}>Upload verification evidence</button>{eMsg&&<div className="accountMessage">{eMsg}</div>}</div>
    {evidence.length>0&&<div className="field full"><strong>Submitted evidence</strong><ul>{evidence.map((x:any)=><li key={x.id}>{x.evidence_type} · {x.file_name}{x.registration_number?` · ${x.registration_number}`:""}</li>)}</ul></div>}
    <div className="sectionLabel">01 · Authorized issuer key</div><div className="field full"><label>Issuer key passphrase</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)}/></div><div className="field full">{pk?<><label>Registered issuer public key</label><code className="publicKey">{pk}</code></>:<button className="button primary" onClick={makeKey}>Create & register issuer key</button>}</div>
    <div className="sectionLabel">02 · Issue document</div><div className="field"><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label>Document type</label><input value={documentType} onChange={e=>setDocumentType(e.target.value)}/></div><div className="field"><label>Subject / recipient</label><input value={subjectName} onChange={e=>setSubjectName(e.target.value)}/></div><div className="field"><label>Original file</label><input type="file" onChange={e=>chooseFile(e.target.files?.[0])}/></div>{assetHash&&<div className="hashBox"><span>ASSET SHA-256</span><code>{assetHash}</code></div>}
    {dups.length>0&&<><div className="sectionLabel">03 · Existing asset relationship</div><div className="field full">{dups.map((d:any)=><label key={d.id} style={{display:"block",marginBottom:8}}><input type="radio" checked={relatedRecordId===d.id} onChange={()=>setRelatedRecordId(d.id)}/> {d.id} · {d.creator_name} · {d.title}</label>)}</div><div className="field"><label>Relationship</label><select value={relationshipType} onChange={e=>setRelationshipType(e.target.value)}><option value="">Choose relationship…</option><option value="co_issuer">Co-issuer</option><option value="co_signatory">Co-signatory</option><option value="attestor">Attestor</option><option value="endorser">Endorser</option></select></div></>}
    <div className="field full"><button className="button primary" disabled={!title||!assetHash||!pk||!pass||(dups.length>0&&!relationshipType)} onClick={issue}>Sign & issue institutional record</button></div>
  </div>{msg&&<div className="accountMessage">{msg}</div>}</section></main>;
}
