"use client";
import Link from "next/link";
import Nav from "@/components/Nav";
export default function TermsPage() {
return <main className="legalRoot"><div className="legalShell"><Nav/>
<header className="legalHero"><p className="legalEyebrow">HPS · TERMS</p><h1>Terms of Service</h1><p>These terms govern use of the Human Provenance Standard website, Research Agent, browser extension, Microsoft Word add-in and related services.</p><div className="legalMeta"><span>Effective 6 September 2026</span><span>Elimara Technologies Limited</span><span>Kenya</span></div></header>
<article className="legalContent">
<section><h2>1. Acceptance</h2><p>By accessing or using HPS, you agree to these Terms and the HPS Privacy Policy. If you do not agree, do not use HPS.</p></section>
<section><h2>2. What HPS provides</h2><p>HPS provides provenance, verification and accountability tools intended to help people and institutions record evidence use, human and AI contribution, review, signatures, attestations and related provenance information.</p><div className="legalCallout"><strong>Important:</strong><p>HPS is a provenance and decision-support system. It is not a truth engine, misconduct tribunal, plagiarism verdict system, legal certification service or guarantee of authorship, scientific quality or factual correctness.</p></div></section>
<section><h2>3. Accounts and access</h2><p>You are responsible for maintaining the security of your account, credentials, signing keys and passphrases. You must not use another person’s account or signing identity without authorisation.</p></section>
<section><h2>4. Provenance records and signatures</h2><p>HPS records may include hashes, public keys, signatures, timestamps, attestations and verification status. A valid signature can show that a specific key signed specific data; it does not by itself prove that every statement is true or that the signer personally created every part of the content.</p><p>You must not create misleading provenance records, impersonate another person or institution, falsely claim signing authority or use HPS to facilitate fraud.</p></section>
<section><h2>5. Research Agent findings</h2><p>The Research Agent may identify citation gaps, unresolved sources, possible contradictions, source-origin concerns or AI-review gaps. These findings support human judgement. Users remain responsible for checking sources, reviewing AI-assisted work and deciding what enters a final output.</p></section>
<section><h2>6. Browser extension and Word add-in</h2><p>HPS extensions and add-ins may access information that you explicitly choose to process, such as the active webpage, selected document content or current manuscript text. You are responsible for ensuring you are authorised to process that material.</p></section>
<section><h2>7. Responsible use</h2><ul><li>Do not impersonate creators, researchers or institutions.</li><li>Do not fabricate signatures, attestations or provenance histories.</li><li>Do not misrepresent AI-generated work as independently verified human work.</li><li>Do not bypass security or access controls.</li><li>Do not process information you are not authorised to use.</li><li>Do not use HPS in violation of applicable law.</li></ul></section>
<section><h2>8. Your content and HPS intellectual property</h2><p>You retain rights you already hold in your documents and research content. You grant HPS only the rights necessary to perform the functions you request, such as hashing, verification, analysis or provenance recording. HPS software, branding, interface design and documentation remain owned by their respective rights holders unless otherwise stated.</p></section>
<section><h2>9. Third-party services</h2><p>HPS may rely on infrastructure, authentication providers, scholarly metadata services or other integrations. Those services may have their own terms and privacy policies.</p></section>
<section><h2>10. Prototype status and availability</h2><p>Some HPS features are early-stage or experimental. Features may change, be interrupted, be replaced or be withdrawn. HPS does not guarantee continuous availability, compatibility with every browser or Office environment, preservation of every local prototype session or uninterrupted access to third-party services.</p></section>
<section><h2>11. Disclaimers</h2><p>HPS is provided on an “as available” basis to the extent permitted by law. HPS does not warrant that the service will be error-free, complete, uninterrupted or legally sufficient for every regulatory, evidentiary or contractual purpose.</p></section>
<section><h2>12. Limitation of liability</h2><p>To the extent permitted by applicable law, HPS and Elimara Technologies Limited will not be liable for indirect, incidental, special or consequential loss arising solely from use of the service, loss of local prototype data, reliance on automated findings, third-party service failure or unauthorised use of credentials or signing keys. Nothing excludes liability that cannot lawfully be excluded.</p></section>
<section><h2>13. Suspension or termination</h2><p>HPS may suspend access where reasonably necessary to protect the service, investigate abuse, comply with law or respond to security risks.</p></section>
<section><h2>14. Changes</h2><p>These Terms may change as HPS evolves. Material changes will be reflected by updating the effective date.</p></section>
<section><h2>15. Governing law</h2><p>Unless mandatory law provides otherwise, these Terms are governed by the laws of Kenya.</p></section>
<section><h2>16. Contact</h2><p><strong>Human Provenance Standard (HPS)</strong><br/>Elimara Technologies Limited<br/>Kenya</p><p><strong>Email:</strong> support@humanprovenancestandard.org</p></section>
<div className="legalLinks"><Link className="legalButton primary" href="/privacy">Privacy</Link><Link className="legalButton" href="/support">Support</Link></div>
</article></div>
<style jsx global>{`
.legalRoot{min-height:100vh;background:#0c0d0f;color:#f1eee7}.legalShell{max-width:1080px;margin:0 auto;padding:58px 24px 90px}.legalHero{max-width:850px;padding:52px 0 34px;border-bottom:1px solid #282a2f}.legalEyebrow{color:#c69a5b;font-size:11px;font-weight:800;letter-spacing:.17em;text-transform:uppercase;margin-bottom:16px}.legalHero h1{font-size:clamp(42px,6vw,70px);line-height:1;letter-spacing:-.045em;margin:0 0 20px}.legalHero p,.legalContent p,.legalContent li{color:#9fa2a7;line-height:1.7}.legalMeta{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.legalMeta span{border:1px solid #33363b;background:#141619;border-radius:999px;color:#92959a;font-size:11px;padding:7px 10px}.legalContent{max-width:820px;margin:34px auto 0}.legalContent section{padding:0 0 28px;margin-bottom:28px;border-bottom:1px solid #24262b}.legalContent h2{font-size:25px;margin:0 0 13px}.legalContent h3{font-size:17px;margin:20px 0 9px}.legalCallout{border:1px solid #35383e;background:#111315;border-radius:14px;padding:17px 18px;margin:18px 0}.legalLinks{display:flex;gap:9px;flex-wrap:wrap;margin-top:32px}.legalButton{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 15px;border-radius:10px;border:1px solid #373a40;background:#17191c;color:#eeeae2;text-decoration:none;font-size:12px;font-weight:750}.legalButton.primary{background:#ede7dc;color:#111315;border-color:#ede7dc}.supportCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.supportCard{border:1px solid #2d3035;background:#101214;border-radius:14px;padding:18px}.supportCode{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#cab28e;background:#0a0c0e;border:1px solid #282b30;border-radius:9px;padding:10px;overflow-wrap:anywhere}
`}</style>
</main>;
}