"use client";
import Link from "next/link";
import Nav from "@/components/Nav";
export default function PrivacyPage() {
return <main className="legalRoot"><div className="legalShell"><Nav/>
<header className="legalHero"><p className="legalEyebrow">HPS · PRIVACY</p><h1>Privacy Policy</h1><p>Human Provenance Standard is designed to record meaningful provenance events without turning research activity into surveillance.</p><div className="legalMeta"><span>Effective 6 September 2026</span><span>Elimara Technologies Limited</span><span>Kenya</span></div></header>
<article className="legalContent">
<section><h2>1. Scope</h2><p>This Privacy Policy applies to the Human Provenance Standard website, HPS Trusted Research Agent, browser extensions, Microsoft Word add-ins, verification and signing services, and related services.</p><div className="legalCallout"><strong>Design principle:</strong><p>Record the research trail, not the researcher.</p></div></section>
<section><h2>2. Information we may process</h2><p>Depending on the feature used, HPS may process account identifiers, creator or issuer identifiers, public keys, signatures, document hashes, timestamps, institutional attestations, record status, source titles and URLs, DOI information, evidence notes, research claims, claim-to-source relationships, AI-assistance disclosures, human-review records, document-audit results and provenance checkpoints.</p></section>
<section><h2>3. Browser extension</h2><p>The browser extension follows an explicit user-approved capture model. When you choose <strong>Save current page as source</strong>, it may record the current page title, URL, timestamp and a provenance event. It may also record AI-assistance disclosures, human-review notes and checkpoints when you deliberately create them.</p><p>The extension is not designed to collect browsing history in the background, keystrokes, passwords, form entries, unrelated tabs or hidden browsing behaviour.</p><p>The extension currently uses permissions such as <strong>activeTab</strong> and <strong>storage</strong>. activeTab is used when you explicitly invoke an HPS action on the active page. storage is used to keep provenance events locally in the browser.</p></section>
<section><h2>4. Sending a browser trail to HPS</h2><p>When you select <strong>Send to HPS</strong>, the extension packages the events you deliberately recorded and transfers them into the HPS Research Agent. In the current prototype, browser provenance may be encoded in the URL fragment of the HPS import page and decoded in the browser.</p></section>
<section><h2>5. Microsoft Word add-in</h2><p>The HPS Word add-in acts when a user deliberately invokes an HPS action. Depending on that action, it may read the current document or selected text, calculate a document hash, perform citation or claim checks, record an AI-assistance disclosure or transfer manuscript content to the HPS Research Agent. It is not designed to continuously record typing or keystrokes.</p></section>
<section><h2>6. DOI and source verification</h2><p>Where you ask HPS to verify a DOI, HPS may send that DOI to an external scholarly metadata service such as Crossref to retrieve bibliographic metadata. External services operate under their own terms and privacy policies.</p></section>
<section><h2>7. Cryptographic keys and signing</h2><p>Where HPS provides local key generation, private signing keys are intended to remain under the user's control. HPS may store public keys, identifiers, signatures and verification information needed to verify provenance records. Users are responsible for protecting private key material and passphrases.</p></section>
<section><h2>8. Documents and hashes</h2><p>HPS seeks to minimise storage of document content where a cryptographic hash can provide the required provenance function. Some workflows may process manuscript text where necessary for a user-requested citation, claim or provenance function. Private document content is not intended to become public merely because a hash or provenance record exists.</p></section>
<section><h2>9. How we use information</h2><ul><li>operate and secure the provenance service;</li><li>verify records and signatures;</li><li>provide citation, evidence-traceability and research-integrity tools;</li><li>maintain research trails and institutional attestations;</li><li>troubleshoot and improve HPS.</li></ul><p>HPS does not sell research trails or personal information for targeted advertising.</p></section>
<section><h2>10. Automated analysis and human review</h2><p>HPS may surface potential provenance, citation or research-integrity issues, including missing citations, unresolved DOI records, source-origin concerns, possible contradictions or AI-review gaps. These are decision-support signals. They are not determinations of truth, misconduct, plagiarism, authorship or research quality.</p></section>
<section><h2>11. Sharing and public records</h2><p>HPS may share information where necessary with service providers, where a user deliberately requests interoperability, where an authorised institutional workflow requires it, where required by law, or to protect service security. Some provenance records are designed to be independently verifiable; information intentionally included in such records may therefore be visible to others.</p></section>
<section><h2>12. Retention</h2><p>HPS retains information only as long as reasonably necessary for the relevant service, legitimate provenance verification, legal obligations and platform security. Some issued records may need to remain historically verifiable and may be revoked, superseded or marked inactive rather than silently deleted.</p></section>
<section><h2>13. Security</h2><p>HPS uses safeguards appropriate to the information being processed, which may include cryptographic hashing, digital signatures, encrypted local key storage, access controls and secure communications. No internet-based system can guarantee absolute security.</p></section>
<section><h2>14. Your rights</h2><p>Depending on applicable law, users may have rights relating to access, correction, deletion, restriction or other processing of personal information. These rights may not always require deletion of historical cryptographic provenance where retention is necessary for integrity, verification or legal compliance.</p></section>
<section><h2>15. Kenya data protection</h2><p>Where Kenyan data-protection law applies, HPS intends to process personal information consistently with the Data Protection Act, 2019 and applicable regulations.</p></section>
<section><h2>16. Changes</h2><p>HPS may update this policy as integrations, APIs, institutional services or provenance capabilities change. Material changes will be reflected by updating the effective date.</p></section>
<section><h2>17. Contact</h2><p><strong>Human Provenance Standard (HPS)</strong><br/>Elimara Technologies Limited<br/>Kenya</p><p><strong>Email:</strong> privacy@humanprovenancestandard.org</p></section>
<div className="legalLinks"><Link className="legalButton primary" href="/terms">Terms</Link><Link className="legalButton" href="/support">Support</Link></div>
</article></div>
<style jsx global>{`
.legalRoot{min-height:100vh;background:#0c0d0f;color:#f1eee7}.legalShell{max-width:1080px;margin:0 auto;padding:58px 24px 90px}.legalHero{max-width:850px;padding:52px 0 34px;border-bottom:1px solid #282a2f}.legalEyebrow{color:#c69a5b;font-size:11px;font-weight:800;letter-spacing:.17em;text-transform:uppercase;margin-bottom:16px}.legalHero h1{font-size:clamp(42px,6vw,70px);line-height:1;letter-spacing:-.045em;margin:0 0 20px}.legalHero p,.legalContent p,.legalContent li{color:#9fa2a7;line-height:1.7}.legalMeta{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.legalMeta span{border:1px solid #33363b;background:#141619;border-radius:999px;color:#92959a;font-size:11px;padding:7px 10px}.legalContent{max-width:820px;margin:34px auto 0}.legalContent section{padding:0 0 28px;margin-bottom:28px;border-bottom:1px solid #24262b}.legalContent h2{font-size:25px;margin:0 0 13px}.legalContent h3{font-size:17px;margin:20px 0 9px}.legalCallout{border:1px solid #35383e;background:#111315;border-radius:14px;padding:17px 18px;margin:18px 0}.legalLinks{display:flex;gap:9px;flex-wrap:wrap;margin-top:32px}.legalButton{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 15px;border-radius:10px;border:1px solid #373a40;background:#17191c;color:#eeeae2;text-decoration:none;font-size:12px;font-weight:750}.legalButton.primary{background:#ede7dc;color:#111315;border-color:#ede7dc}.supportCards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.supportCard{border:1px solid #2d3035;background:#101214;border-radius:14px;padding:18px}.supportCode{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#cab28e;background:#0a0c0e;border:1px solid #282b30;border-radius:9px;padding:10px;overflow-wrap:anywhere}
`}</style>
</main>;
}